import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import building from "../../assets/building.png";
import documentsIllustration from "../../assets/OBJECTS.png";
import PackagesSection from "./company-details/PackagesSection";
import ProcessSection from "./company-details/ProcessSection";
import DocumentsSection from "./company-details/DocumentsSection";
import PrerequisitesSection from "./company-details/PrerequisitesSection";
import AboutSection from "./company-details/AboutSection";
import FAQSection from "./company-details/FAQSection";
import TopTabs from "./company-details/TopTabs";
import { initPayment } from "../../utils/payment";

function Section8Details() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("packages");
  const [expandedSection, setExpandedSection] = useState("");
  const [hidePackagesTab, setHidePackagesTab] = useState(false);
  const [isInFlow, setIsInFlow] = useState(false);

  // Ensure we start with packages tab on mount
  useEffect(() => {
    setActiveTab("packages");
    setExpandedSection("");
    setIsInFlow(false);
    setHidePackagesTab(false);
  }, []);

  // Define the sequential flow steps
  const flowSteps = ["process", "documents", "prerequisites", "about", "faq"];
  
  const getCurrentStepIndex = () => {
    return flowSteps.indexOf(activeTab);
  };

  const handleNext = () => {
    const currentIndex = getCurrentStepIndex();
    if (currentIndex < flowSteps.length - 1) {
      setActiveTab(flowSteps[currentIndex + 1]);
      window.scrollTo({ top: 0, behavior: "smooth" });
    }
  };

  const handleBack = () => {
    const currentIndex = getCurrentStepIndex();
    if (currentIndex === 0) {
      // Go back to packages and exit flow
      setActiveTab("packages");
      setIsInFlow(false);
      setHidePackagesTab(false);
    } else {
      setActiveTab(flowSteps[currentIndex - 1]);
    }
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const aboutSections = [
    {
      id: "what-is-section8",
      title: "What is a Section 8 Company?",
      content: "A Section 8 Company is a legal entity set up for non-profit activities, such as education, social welfare, sports, charity, and more. The purpose of registering a Section 8 Company is to promote these non-profitable goals. These companies utilize their profits solely to achieve their mission and do not distribute dividends to shareholders. A minimum of two directors is required to form such a company, and there is no requirement for a minimum paid-up capital.\n\nAt OnEasy, we offer end-to-end services for registering Section 8 companies in India. Our team of experts ensures a smooth and professional process to help you establish a Section 8 company swiftly and efficiently.\n\nContact us today to take advantage of our specialized services for registering your Section 8 Company."
    },
    {
      id: "key-points",
      title: "Key Points About Section 8 Companies",
      content: [
        {
          title: "Registration Options",
          description: "In India, Non-Governmental Organizations (NGOs) can either be registered under the Registrar of Societies or as a non-profit entity under Section 8 of the Companies Act, 2013."
        },
        {
          title: "Profit Utilization",
          description: "Profits generated by Section 8 Companies cannot be used for purposes other than their stated charitable objectives."
        },
        {
          title: "Compliance Requirements",
          description: "Section 8 Companies must comply with the provisions of the Companies Act 2013, including maintaining books of accounts, filing returns with the Registrar of Companies (ROCs), and adhering to the GST and IT Act."
        },
        {
          title: "Document Changes",
          description: "Changes to key documents like the Articles of Association (AOA) or Memorandum of Association (MOA) require government approval."
        }
      ]
    },
    {
      id: "advantages",
      title: "Advantages of Incorporating as a Section 8 Company",
      content: [
        {
          title: "Tax Exemption",
          description: "Companies registered under Section 12AA of the Income Tax Act are eligible for a 100% tax exemption as their profits are utilized for charitable purposes."
        },
        {
          title: "No Minimum Capital Requirement",
          description: "Section 8 Companies are not required to maintain a minimum capital and can adjust their capital based on their needs."
        },
        {
          title: "Separate Legal Entity",
          description: "A Section 8 Company is recognized as a separate legal entity with perpetual existence."
        },
        {
          title: "Increased Credibility",
          description: "Due to the strict compliance requirements, Section 8 Companies hold higher credibility compared to NGOs or trusts."
        },
        {
          title: "No Title Requirement",
          description: "Section 8 Companies are not obligated to add \"Section 8\" or \"Ltd.\" to their name."
        }
      ]
    },
    {
      id: "incorporation-process",
      title: "Incorporation Process of a Section 8 Company",
      content: [
        {
          title: "Reserve the Company Name",
          description: "The proposed company name is reserved with the Ministry of Corporate Affairs (MCA)."
        },
        {
          title: "File the Incorporation Application",
          description: "After the name is approved, the incorporation application is filed along with the MOA and AOA."
        },
        {
          title: "Obtain License",
          description: "A license for the Section 8 Company is obtained from the MCA."
        },
        {
          title: "Obtain Certificate of Incorporation",
          description: "The final step involves obtaining the Certificate of Incorporation from the MCA."
        }
      ]
    },
    {
      id: "donations-funding",
      title: "Donations and Funding for a Section 8 Company",
      content: "Section 8 Companies can accept donations from the public but cannot raise capital through deposits. They can also receive foreign contributions after registering under FCRA."
    },
    {
      id: "why-oneasy",
      title: "Why Choose OnEasy for Section 8 Company Registration?",
      content: "Streamline your Section 8 Company registration with OnEasy. Our team ensures a seamless process, guiding you through every step to establish your non-profit organization efficiently. Contact us today to get started!"
    }
  ];

  const tabs = [
    { id: "packages", label: "Packages" },
    { id: "process", label: "Process" },
    { id: "documents", label: "Documents" },
    { id: "prerequisites", label: "Pre requisites" },
    { id: "about", label: "About" },
    { id: "faq", label: "FAQ" },
  ];

  // Filter out packages tab if it should be hidden
  const visibleTabs = hidePackagesTab || isInFlow
    ? tabs.filter((tab) => tab.id !== "packages")
    : tabs;

  // Packages - same as Private Limited Company
  const packages = [
    {
      name: "Starter",
      price: "12,999",
      priceValue: 12999,
      period: "One Time",
      description: "For solo entrepreneurs",
      icon: "★",
      features: [
        "Company Name Reservation",
        "DSC for Director",
        "DIN Application",
        "MOA & AOA Drafting",
        "SPICe+ Form Filing",
        "Certificate of Incorporation",
        "PAN & TAN Application",
        "GST Registration (if applicable)"
      ],
      color: "blue",
    },
    {
      name: "Growth",
      price: "16,999",
      priceValue: 16999,
      period: "One Time",
      description: "As your business scales",
      icon: "✢",
      features: [
        "Everything in Starter",
        "Professional Tax Registration",
        "Shops & Establishment License",
        "MSME Registration",
        "Bank Account Opening Assistance",
        "CA Consultation (15 mins)",
        "Priority Support"
      ],
      isHighlighted: true,
      color: "blue",
    },
    {
      name: "Pro",
      price: "25,499",
      priceValue: 25499,
      period: "One Time",
      description: "For more complex businesses",
      icon: "✤",
      features: [
        "Everything in Growth",
        "Startup India Registration",
        "FSSAI License (if applicable)",
        "Trade License",
        "CA Consultation (30 mins)",
        "Dedicated Account Manager",
        "1 Year Compliance Support",
        "Legal Document Templates"
      ],
      color: "blue",
    },
  ];

  const processSteps = [
    {
      step: 1,
      title: "Reserve the Company Name",
      description: "The proposed company name is reserved with the Ministry of Corporate Affairs (MCA)."
    },
    {
      step: 2,
      title: "File the Incorporation Application",
      description: "After the name is approved, the incorporation application is filed along with the MOA and AOA."
    },
    {
      step: 3,
      title: "Obtain License",
      description: "A license for the Section 8 Company is obtained from the MCA."
    },
    {
      step: 4,
      title: "Obtain Certificate of Incorporation",
      description: "The final step involves obtaining the Certificate of Incorporation from the MCA."
    }
  ];

  const prerequisites = [
    "Any Indian national or Hindu Undivided Family (HUF) can incorporate a Section 8 Company.",
    "A minimum of two directors for private limited and three for public limited companies.",
    "A private limited structure limits the number of members to 200, while there's no cap for public limited entities.",
    "There is no requirement for a minimum paid-up capital. Additionally, Section 8 entities are not required to use \"private limited\" or \"limited\" in their names.",
    "The goals must be non-profit-oriented, and any profits must be used for charitable purposes or reinvested in the company.",
    "Resolution by the promoter company is required to convert an existing company into a Section 8 company."
  ];

  const documents = [
    "PAN Card of all Directors",
    "Aadhaar Card of all Directors",
    "Bank Statement of all Directors (Recent)",
    "Photograph of all the Directors",
    "Declaration by the first directors",
    "Declaration by subscribers",
    "Proof of Registered office address",
    "Resolution by the promoter company"
  ];

  const faqItems = [
    {
      question: "What is a Section 8 Company?",
      answer: "A Section 8 Company is a non-profit organization formed under the Companies Act, 2013, with the primary objective to promote charity, education, arts, commerce, science, sports, environmental protection, or social welfare. The profits from these companies are used to promote the company's objectives, not for distribution among its members."
    },
    {
      question: "What are the key benefits of incorporating a Section 8 Company?",
      answer: "The key benefits include tax exemptions, no minimum capital requirement, increased credibility, separate legal entity status, and exemptions from stamp duty."
    },
    {
      question: "What are the eligibility criteria for forming a Section 8 Company?",
      answer: "Any individual or organization that wants to promote charitable or social welfare activities can form a Section 8 Company. At least two directors are required, and the primary objective must be non-profit."
    },
    {
      question: "Is there a minimum capital requirement for a Section 8 Company?",
      answer: "No, there is no minimum paid-up capital required to incorporate a Section 8 Company. The capital structure can be flexible as per the company's needs."
    },
    {
      question: "How many members and directors are required for a Section 8 Company?",
      answer: "A minimum of two directors are required for private limited structures, and three for public limited companies. For a private limited Section 8 Company, the maximum number of members is capped at 200."
    },
    {
      question: "Can a Section 8 Company distribute its profits or dividends to its members?",
      answer: "No, a Section 8 Company cannot distribute any profits or dividends to its members. All profits must be reinvested to further the company's objectives."
    },
    {
      question: "What documents are required for Section 8 Company incorporation?",
      answer: "The key documents required include the Memorandum of Association (MOA), Articles of Association (AOA), identity and address proof of directors and proof of registered office."
    },
    {
      question: "What is the process for registering a Section 8 Company?",
      answer: "The process includes reserving the company's name, drafting MOA and AOA, filing incorporation forms with the Ministry of Corporate Affairs (MCA), obtaining a license for the Section 8 Company, and finally receiving a Certificate of Incorporation."
    },
    {
      question: "Are Section 8 Companies eligible for tax exemptions?",
      answer: "Yes, Section 8 Companies can apply for tax exemptions under the Income Tax Act, 1961, such as Section 12AA and Section 80G, which allows donors to claim tax benefits."
    },
    {
      question: "Can a Section 8 Company receive foreign donations?",
      answer: "Yes, but Section 8 Companies need to be registered under the Foreign Contribution Regulation Act (FCRA) to accept foreign contributions. If immediate foreign donations are required, prior permission from the government can be obtained."
    }
  ];

  const handleGetStarted = async (pkg) => {
    try {
      console.log('💳 Initiating payment for Section 8 Company:', pkg);

      // Store registration type and package in localStorage
      localStorage.setItem('selectedRegistrationType', 'section-8');
      localStorage.setItem('selectedRegistrationTitle', 'Section 8 Company Registration');

      // Initiate payment
      const result = await initPayment({
        name: `Section 8 - ${pkg.name}`,
        price: pkg.price,
        priceValue: pkg.priceValue,
        ...pkg
      });

      if (result.success && result.redirect) {
        console.log('✅ Payment successful! Redirecting to form...');
        navigate('/section-8-form');
      }
    } catch (error) {
      console.error('Payment error:', error);
      if (error.message !== 'Payment cancelled') {
        alert(`Payment failed: ${error.message || 'Please try again'}`);
      }
    }
  };

  const handleContinue = () => {
    // Navigate to Section 8 form page
    navigate("/section-8-form");
  };

  const renderTabContent = () => {
    switch (activeTab) {
      case "packages":
        return (
          <PackagesSection
            packages={packages}
            onGetStarted={handleGetStarted}
          />
        );

      case "process":
        return <ProcessSection processSteps={processSteps} />;

      case "documents":
        return <DocumentsSection documents={documents} illustration={documentsIllustration} />;

      case "prerequisites":
        return <PrerequisitesSection prerequisites={prerequisites} />;

      case "about":
        return (
          <AboutSection
            building={building}
            aboutSections={aboutSections}
            expandedSection={expandedSection}
            setExpandedSection={setExpandedSection}
            introTitle="About Section 8 Company"
            introDescription="A Section 8 Company is a non-profit organization that promotes charitable activities, art, science, education, and sports. The profits of such companies are utilized to support these objectives and are not distributed among the members."
          />
        );

      case "faq":
        return <FAQSection faqs={faqItems} />;

      default:
        return null;
    }
  };

  // Check if current tab is in the flow steps
  const isInFlowStep = flowSteps.includes(activeTab);
  // Don't show navigation buttons on FAQ tab (removed Continue button)
  const showNavigationButtons = isInFlow && isInFlowStep && activeTab !== "faq";
  
  // Show Continue button only on FAQ, Next on all other flow steps
  const isLastStep = activeTab === "faq";

  return (
    <div className="min-h-screen bg-[#f3f5f7]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* My Registrations Button - Top Right */}
        <div className="flex justify-end mb-4">
          <button
            onClick={() => navigate('/registrations')}
            className="flex items-center gap-2 px-5 py-2.5 bg-[#01334C] text-white rounded-lg hover:bg-[#00486D] transition-colors font-medium shadow-sm"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            My Registrations
          </button>
        </div>

        {/* Tabs - show always so users know where they are */}
        <TopTabs
          tabs={visibleTabs}
          activeTab={activeTab}
          onChange={(id) => {
            // Only allow tab changes if not in flow, or if clicking on a flow step
            if (!isInFlow || flowSteps.includes(id) || id === "faq") {
              setActiveTab(id);
            }
          }}
          disabled={isInFlow}
        />
        {renderTabContent()}
        {showNavigationButtons && (
          <div className=" mt-8 px-8  mb-4">
            <div className="flex justify-between items-center">
              <button
                onClick={handleBack}
                className="px-6 py-2 border border-[#00486D] text-[#00486D] rounded-lg font-semibold transition-all duration-300 hover:bg-[#00486D] hover:text-white cursor-pointer"
              >
                Back
              </button>
              {isLastStep ? (
                <button
                  onClick={handleContinue}
                  className="px-6 py-2 bg-[#00486D] text-white rounded-lg font-semibold transition-all duration-300 hover:bg-[#01334C] cursor-pointer"
                >
                  Continue
                </button>
              ) : (
                <button
                  onClick={handleNext}
                  className="px-6 py-2 bg-[#00486D] text-white rounded-lg font-semibold transition-all duration-300 hover:bg-[#01334C] cursor-pointer"
                >
                  Next
                </button>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default Section8Details;

